### ISSUE TITLE
Issue for react css module

### ISSUE THREAD

**Issue by daranmikate** [mytabworks/mytabworks-react-select#2]
The react css module cannot override the mytabworks-react-select styles

**Comment by mytabworks** [comment]
@daranmikate you can easily achieved overriding in normal css import since the library is supported on adding the className in the select container, like this
`
.selector  .selector-facade {
    padding:10px 20px;
}
`
or you can do something like this
`
.selector.custom  .selector-facade {
   padding:10px 20px;
}
`
so that the original style will not be affected whenever you need the original style in another forms.
however since you mention _react css module_ like scss(sass), it is programmatically change the name of all the class into unique name  so it will not affected the other css, the problem is the nested classes are inlcuded. so normally if you do this below
`
.sample {
   .selector-facade {
       padding:10px 20px;
   }
}
`
it will be rendered like this below in html build
`
.unique_folder_sample  .unque_folder_selector_facade {
   padding:10px 20px;
}
`
that is why it would be a problem since the **mytabworks-react-select** only allows you to add a  className in container. because obviously, there is no such classes like _unque_folder_selector_facade_ in the library's rendered. that is why it will not be overridden. although it is bound to happen in _react module css_. there are still a solution like nested **:global** to prevent from mutating the name of the nested classes, so that the style will be overridden
`
.sample { 
  /*use nested :global to not mutate the class name of descendant*/
  :global {
    .selector-facade {
      padding:10px 20px;
    }

    li.option {
      padding: 20px !important;
    }
  }
}
`
it will be rendered like this
`
.unique_folder_sample  .selector-facade {
    padding:10px 20px;
}

.unique_folder_sample  li.option {
    padding: 20px !important;
}
`
